name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # Step 1: Generate metrics SVG
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 30
          plugin_wakatime_sections: time, os, languages-graphs
          plugin_wakatime_limit: 4
          plugin_wakatime_url: https://waka.wushiqwq.cn
          plugin_wakatime_user: wushi
          filename: github-metrics.svg
          # Don't commit yet, just generate
          config_output: github-metrics.svg
          
      # Step 2: Prepare distribution directory
      - name: Prepare dist directory
        run: |
          mkdir -p dist
          mv github-metrics.svg dist/ || cp github-metrics.svg dist/
          
      # Step 3: Force push to moutput branch (clean every time)
      - name: Deploy to moutput branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: moutput
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
