name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 30
          plugin_wakatime_sections: time, os, languages-graphs
          plugin_wakatime_limit: 4
          plugin_wakatime_url: https://waka.wushiqwq.cn
          plugin_wakatime_user: wushi
          output_action: none
          filename: github-metrics.svg
          
      - name: Prepare dist directory
        run: |
          mkdir -p dist
          cp github-metrics.svg dist/github-metrics.svg
          ls -la dist/
          
      - name: Deploy to moutput branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: moutput
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
